# Generated by Django 4.1 on 2022-08-20 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\9\\d{2}/')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('\\7\\d{10}/')]),
        ),
    ]
