# Generated by Django 4.1 on 2022-08-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_client_phone_number_alter_client_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='filter_op_codes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='filter_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
