# Generated by Django 4.1 on 2022-08-20 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_mailinglist_filter_op_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='datetime_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='datetime_start',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='messagetosend',
            name='datetime_sent',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
