# Generated by Django 4.1 on 2022-08-20 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_mailinglist_datetime_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 21, 24, 27, 479933, tzinfo=datetime.timezone.utc)),
        ),
    ]
