# Generated by Django 4.1 on 2022-08-21 15:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_mailinglist_datetime_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetosend',
            name='sent_to',
        ),
        migrations.AddField(
            model_name='messagetosend',
            name='sending_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.client'),
        ),
        migrations.AddField(
            model_name='messagetosend',
            name='start_sending',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='messagetosend',
            name='stop_sending',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
