# Generated by Django 4.1 on 2022-08-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_messagetosend_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetosend',
            name='start_sending',
        ),
        migrations.RemoveField(
            model_name='messagetosend',
            name='stop_sending',
        ),
        migrations.RemoveField(
            model_name='messagetosend',
            name='text',
        ),
    ]
